/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalitikRouteImport } from './routes/analitik'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as InputRouteImport } from './routes/input'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MasterRouteImport } from './routes/master'
import { Route as QmsRouteImport } from './routes/qms'
import { Route as MasterDefectTypesRouteImport } from './routes/master.defect-types'
import { Route as MasterMejaRouteImport } from './routes/master.meja'
import { Route as MasterPartRouteImport } from './routes/master.part'
import { Route as MasterUsersRouteImport } from './routes/master.users'
import { Route as QmsAuditRouteImport } from './routes/qms.audit'
import { Route as QmsImprovementRouteImport } from './routes/qms.improvement'
import { Route as QmsNcRouteImport } from './routes/qms.nc'
import { Route as QmsReviewRouteImport } from './routes/qms.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalitikRoute = AnalitikRouteImport.update({
  id: '/analitik',
  path: '/analitik',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const InputRoute = InputRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const QmsRoute = QmsRouteImport.update({
  id: '/qms',
  path: '/qms',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDefectTypesRoute = MasterDefectTypesRouteImport.update({
  id: '/defect-types',
  path: '/defect-types',
  getParentRoute: () => MasterRoute,
} as any)
const MasterMejaRoute = MasterMejaRouteImport.update({
  id: '/meja',
  path: '/meja',
  getParentRoute: () => MasterRoute,
} as any)
const MasterPartRoute = MasterPartRouteImport.update({
  id: '/part',
  path: '/part',
  getParentRoute: () => MasterRoute,
} as any)
const MasterUsersRoute = MasterUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => MasterRoute,
} as any)
const QmsAuditRoute = QmsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => QmsRoute,
} as any)
const QmsImprovementRoute = QmsImprovementRouteImport.update({
  id: '/improvement',
  path: '/improvement',
  getParentRoute: () => QmsRoute,
} as any)
const QmsNcRoute = QmsNcRouteImport.update({
  id: '/nc',
  path: '/nc',
  getParentRoute: () => QmsRoute,
} as any)
const QmsReviewRoute = QmsReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => QmsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analitik': typeof AnalitikRoute
  '/builder': typeof BuilderRoute
  '/input': typeof InputRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRouteWithChildren
  '/qms': typeof QmsRouteWithChildren
  '/master/defect-types': typeof MasterDefectTypesRoute
  '/master/meja': typeof MasterMejaRoute
  '/master/part': typeof MasterPartRoute
  '/master/users': typeof MasterUsersRoute
  '/qms/audit': typeof QmsAuditRoute
  '/qms/improvement': typeof QmsImprovementRoute
  '/qms/nc': typeof QmsNcRoute
  '/qms/review': typeof QmsReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analitik': typeof AnalitikRoute
  '/builder': typeof BuilderRoute
  '/input': typeof InputRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRouteWithChildren
  '/qms': typeof QmsRouteWithChildren
  '/master/defect-types': typeof MasterDefectTypesRoute
  '/master/meja': typeof MasterMejaRoute
  '/master/part': typeof MasterPartRoute
  '/master/users': typeof MasterUsersRoute
  '/qms/audit': typeof QmsAuditRoute
  '/qms/improvement': typeof QmsImprovementRoute
  '/qms/nc': typeof QmsNcRoute
  '/qms/review': typeof QmsReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analitik': typeof AnalitikRoute
  '/builder': typeof BuilderRoute
  '/input': typeof InputRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRouteWithChildren
  '/qms': typeof QmsRouteWithChildren
  '/master/defect-types': typeof MasterDefectTypesRoute
  '/master/meja': typeof MasterMejaRoute
  '/master/part': typeof MasterPartRoute
  '/master/users': typeof MasterUsersRoute
  '/qms/audit': typeof QmsAuditRoute
  '/qms/improvement': typeof QmsImprovementRoute
  '/qms/nc': typeof QmsNcRoute
  '/qms/review': typeof QmsReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analitik'
    | '/builder'
    | '/input'
    | '/laporan'
    | '/login'
    | '/master'
    | '/qms'
    | '/master/defect-types'
    | '/master/meja'
    | '/master/part'
    | '/master/users'
    | '/qms/audit'
    | '/qms/improvement'
    | '/qms/nc'
    | '/qms/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analitik'
    | '/builder'
    | '/input'
    | '/laporan'
    | '/login'
    | '/master'
    | '/qms'
    | '/master/defect-types'
    | '/master/meja'
    | '/master/part'
    | '/master/users'
    | '/qms/audit'
    | '/qms/improvement'
    | '/qms/nc'
    | '/qms/review'
  id:
    | '__root__'
    | '/'
    | '/analitik'
    | '/builder'
    | '/input'
    | '/laporan'
    | '/login'
    | '/master'
    | '/qms'
    | '/master/defect-types'
    | '/master/meja'
    | '/master/part'
    | '/master/users'
    | '/qms/audit'
    | '/qms/improvement'
    | '/qms/nc'
    | '/qms/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalitikRoute: typeof AnalitikRoute
  BuilderRoute: typeof BuilderRoute
  InputRoute: typeof InputRoute
  LaporanRoute: typeof LaporanRoute
  LoginRoute: typeof LoginRoute
  MasterRoute: typeof MasterRouteWithChildren
  QmsRoute: typeof QmsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analitik': {
      id: '/analitik'
      path: '/analitik'
      fullPath: '/analitik'
      preLoaderRoute: typeof AnalitikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/input': {
      id: '/input'
      path: '/input'
      fullPath: '/input'
      preLoaderRoute: typeof InputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qms': {
      id: '/qms'
      path: '/qms'
      fullPath: '/qms'
      preLoaderRoute: typeof QmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/defect-types': {
      id: '/master/defect-types'
      path: '/defect-types'
      fullPath: '/master/defect-types'
      preLoaderRoute: typeof MasterDefectTypesRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/meja': {
      id: '/master/meja'
      path: '/meja'
      fullPath: '/master/meja'
      preLoaderRoute: typeof MasterMejaRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/part': {
      id: '/master/part'
      path: '/part'
      fullPath: '/master/part'
      preLoaderRoute: typeof MasterPartRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/users': {
      id: '/master/users'
      path: '/users'
      fullPath: '/master/users'
      preLoaderRoute: typeof MasterUsersRouteImport
      parentRoute: typeof MasterRoute
    }
    '/qms/audit': {
      id: '/qms/audit'
      path: '/audit'
      fullPath: '/qms/audit'
      preLoaderRoute: typeof QmsAuditRouteImport
      parentRoute: typeof QmsRoute
    }
    '/qms/improvement': {
      id: '/qms/improvement'
      path: '/improvement'
      fullPath: '/qms/improvement'
      preLoaderRoute: typeof QmsImprovementRouteImport
      parentRoute: typeof QmsRoute
    }
    '/qms/nc': {
      id: '/qms/nc'
      path: '/nc'
      fullPath: '/qms/nc'
      preLoaderRoute: typeof QmsNcRouteImport
      parentRoute: typeof QmsRoute
    }
    '/qms/review': {
      id: '/qms/review'
      path: '/review'
      fullPath: '/qms/review'
      preLoaderRoute: typeof QmsReviewRouteImport
      parentRoute: typeof QmsRoute
    }
  }
}

interface MasterRouteChildren {
  MasterDefectTypesRoute: typeof MasterDefectTypesRoute
  MasterMejaRoute: typeof MasterMejaRoute
  MasterPartRoute: typeof MasterPartRoute
  MasterUsersRoute: typeof MasterUsersRoute
}

const MasterRouteChildren: MasterRouteChildren = {
  MasterDefectTypesRoute: MasterDefectTypesRoute,
  MasterMejaRoute: MasterMejaRoute,
  MasterPartRoute: MasterPartRoute,
  MasterUsersRoute: MasterUsersRoute,
}

const MasterRouteWithChildren =
  MasterRoute._addFileChildren(MasterRouteChildren)

interface QmsRouteChildren {
  QmsAuditRoute: typeof QmsAuditRoute
  QmsImprovementRoute: typeof QmsImprovementRoute
  QmsNcRoute: typeof QmsNcRoute
  QmsReviewRoute: typeof QmsReviewRoute
}

const QmsRouteChildren: QmsRouteChildren = {
  QmsAuditRoute: QmsAuditRoute,
  QmsImprovementRoute: QmsImprovementRoute,
  QmsNcRoute: QmsNcRoute,
  QmsReviewRoute: QmsReviewRoute,
}

const QmsRouteWithChildren = QmsRoute._addFileChildren(QmsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalitikRoute: AnalitikRoute,
  BuilderRoute: BuilderRoute,
  InputRoute: InputRoute,
  LaporanRoute: LaporanRoute,
  LoginRoute: LoginRoute,
  MasterRoute: MasterRouteWithChildren,
  QmsRoute: QmsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
