/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MasterRouteImport } from './routes/master'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as InputRouteImport } from './routes/input'
import { Route as AnalitikRouteImport } from './routes/analitik'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MasterUsersRouteImport } from './routes/master.users'
import { Route as MasterPartRouteImport } from './routes/master.part'
import { Route as MasterMejaRouteImport } from './routes/master.meja'
import { Route as MasterDefectTypesRouteImport } from './routes/master.defect-types'

const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const InputRoute = InputRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalitikRoute = AnalitikRouteImport.update({
  id: '/analitik',
  path: '/analitik',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterUsersRoute = MasterUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => MasterRoute,
} as any)
const MasterPartRoute = MasterPartRouteImport.update({
  id: '/part',
  path: '/part',
  getParentRoute: () => MasterRoute,
} as any)
const MasterMejaRoute = MasterMejaRouteImport.update({
  id: '/meja',
  path: '/meja',
  getParentRoute: () => MasterRoute,
} as any)
const MasterDefectTypesRoute = MasterDefectTypesRouteImport.update({
  id: '/defect-types',
  path: '/defect-types',
  getParentRoute: () => MasterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analitik': typeof AnalitikRoute
  '/input': typeof InputRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRouteWithChildren
  '/master/defect-types': typeof MasterDefectTypesRoute
  '/master/meja': typeof MasterMejaRoute
  '/master/part': typeof MasterPartRoute
  '/master/users': typeof MasterUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analitik': typeof AnalitikRoute
  '/input': typeof InputRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRouteWithChildren
  '/master/defect-types': typeof MasterDefectTypesRoute
  '/master/meja': typeof MasterMejaRoute
  '/master/part': typeof MasterPartRoute
  '/master/users': typeof MasterUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analitik': typeof AnalitikRoute
  '/input': typeof InputRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRouteWithChildren
  '/master/defect-types': typeof MasterDefectTypesRoute
  '/master/meja': typeof MasterMejaRoute
  '/master/part': typeof MasterPartRoute
  '/master/users': typeof MasterUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analitik'
    | '/input'
    | '/laporan'
    | '/login'
    | '/master'
    | '/master/defect-types'
    | '/master/meja'
    | '/master/part'
    | '/master/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analitik'
    | '/input'
    | '/laporan'
    | '/login'
    | '/master'
    | '/master/defect-types'
    | '/master/meja'
    | '/master/part'
    | '/master/users'
  id:
    | '__root__'
    | '/'
    | '/analitik'
    | '/input'
    | '/laporan'
    | '/login'
    | '/master'
    | '/master/defect-types'
    | '/master/meja'
    | '/master/part'
    | '/master/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalitikRoute: typeof AnalitikRoute
  InputRoute: typeof InputRoute
  LaporanRoute: typeof LaporanRoute
  LoginRoute: typeof LoginRoute
  MasterRoute: typeof MasterRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/input': {
      id: '/input'
      path: '/input'
      fullPath: '/input'
      preLoaderRoute: typeof InputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analitik': {
      id: '/analitik'
      path: '/analitik'
      fullPath: '/analitik'
      preLoaderRoute: typeof AnalitikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/users': {
      id: '/master/users'
      path: '/users'
      fullPath: '/master/users'
      preLoaderRoute: typeof MasterUsersRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/part': {
      id: '/master/part'
      path: '/part'
      fullPath: '/master/part'
      preLoaderRoute: typeof MasterPartRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/meja': {
      id: '/master/meja'
      path: '/meja'
      fullPath: '/master/meja'
      preLoaderRoute: typeof MasterMejaRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/defect-types': {
      id: '/master/defect-types'
      path: '/defect-types'
      fullPath: '/master/defect-types'
      preLoaderRoute: typeof MasterDefectTypesRouteImport
      parentRoute: typeof MasterRoute
    }
  }
}

interface MasterRouteChildren {
  MasterDefectTypesRoute: typeof MasterDefectTypesRoute
  MasterMejaRoute: typeof MasterMejaRoute
  MasterPartRoute: typeof MasterPartRoute
  MasterUsersRoute: typeof MasterUsersRoute
}

const MasterRouteChildren: MasterRouteChildren = {
  MasterDefectTypesRoute: MasterDefectTypesRoute,
  MasterMejaRoute: MasterMejaRoute,
  MasterPartRoute: MasterPartRoute,
  MasterUsersRoute: MasterUsersRoute,
}

const MasterRouteWithChildren =
  MasterRoute._addFileChildren(MasterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalitikRoute: AnalitikRoute,
  InputRoute: InputRoute,
  LaporanRoute: LaporanRoute,
  LoginRoute: LoginRoute,
  MasterRoute: MasterRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
