// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error(
      "Missing Supabase environment variables. Ensure SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY (or VITE_ prefixed versions) are set in your .env file.",
    );
  }

  const devNoopLock =
    typeof window !== "undefined" && import.meta.env.DEV
      ? async <T>(_name: string, _acquireTimeout: number, fn: () => PromiseLike<T>) => await fn()
      : undefined;

  // "Remember me" off = session-only persistence. The flag lives in
  // sessionStorage so it naturally dies with the tab.
  const sessionOnly =
    typeof window !== "undefined" && sessionStorage.getItem(SESSION_ONLY_KEY) === "1";

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage:
        typeof window === "undefined" ? undefined : sessionOnly ? sessionStorage : localStorage,
      persistSession: true,
      autoRefreshToken: true,
      lock: devNoopLock,
    },
  });
}

export const SESSION_ONLY_KEY = "ipp_session_only";

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

/** Drop the cached client so the next access boots a fresh one.
 * Needed when the auth storage mode changes (remember-me toggle);
 * the surrounding AuthProvider resubscribes on the new instance. */
export function resetSupabaseClient() {
  _supabase = undefined;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
